<?php

if(!class_exists('SurveyOfficer')){
   include_once(CLASSES_PATH.'/class.SurveyOfficer.php');
}


$TPL_STRINGS['FORMS_ACTION_URL']           = LIVE_SITE_URL.'/admin/';
$TPL_STRINGS['CAPTION_MYSURVEYS']          = TPL_ADMIN_CAPTION_MYSURVEYS;
$TPL_STRINGS['CAPTION_MYSURVEYS_RUNNING']  = TPL_ADMIN_CAPTION_MYSURVEYS_RUNNING;
$TPL_STRINGS['CAPTION_MYSURVEYS_FINISHED'] = TPL_ADMIN_CAPTION_MYSURVEYS_FINISHED;


$TPL_STRINGS['CAPTION_BUTTON_ADD_SURVEY'] = TPL_ADMIN_CAPTION_BUTTON_ADD_SURVEY;

$TPL_STRINGS['CAPTION_SORT_SURVEYS']             = TPL_ADMIN_CAPTION_SORT_SURVEYS;
$TPL_STRINGS['CAPTION_SORT_SURVEYS_BY']          = TPL_ADMIN_CAPTION_SORT_SURVEYS_BY;
$TPL_STRINGS['CAPTION_SORT_SURVEYS_BY_DATE']     = TPL_ADMIN_CAPTION_SORT_SURVEYS_BY_DATE;
$TPL_STRINGS['CAPTION_SORT_SURVEYS_BY_CREATION'] = TPL_ADMIN_CAPTION_SORT_SURVEYS_BY_CREATION;


$TPL_STRINGS['CAPTION_SORT_SURVEYS_BY_DATE_HREF']     = '';
$TPL_STRINGS['CAPTION_SORT_SURVEYS_BY_CREATION_HREF'] = "javascript:_d('sortSurvey', 'creation');";



$TPL_STRINGS['CAPTION_MYSURVEYS_RUNNING_URL']  = TPL_ADMIN_CAPTION_MYSURVEYS_RUNNING_URL;
$TPL_STRINGS['CAPTION_MYSURVEYS_FINISHED_URL'] = TPL_ADMIN_CAPTION_MYSURVEYS_FINISHED_URL;


$TPL_STRINGS['CAPTION_BUTTON_ADD_SURVIVORS']       = TPL_ADMIN_CAPTION_BUTTON_ADD_SURVIVORS;
$TPL_STRINGS['CAPTION_BUTTON_ADD_SURVIVORS_TITLE'] = TPL_ADMIN_CAPTION_BUTTON_ADD_SURVIVORS_TITLE;

$TPL_STRINGS['BOXES']['INFOBOX'] = array('TITLE' => TPL_ADMIN_SIDEBOX_TITLE,
'BODY' => TPL_ADMIN_SIDEBOX_BODY);
$TPL_STRINGS['BOXES']['INFOBOX2'] = array('TITLE' => TPL_ADMIN_SIDEBOX_TITLE,
'BODY' => TPL_ADMIN_SIDEBOX_BODY);

?>